config/routes.rb
Rails.application.routes.draw do
  get 'home/help'
  devise_for :users
  resources :lessons
  resources :students
  resources :quotes

  root 'students#index'

  get 'new_lesson' => 'lessons#new'
  get 'show_student' => 'students#show'
  get 'lessons_by_student' => 'lessons#lessons_by_student', as: 'student_lessons'
  get 'new_quote'=> 'quotes#new'
  get 'quotes' => 'quotes#index'
  get 'help' => 'home#help'

  mount Resque::Server, :at => "/resque"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/quote.rb
class Quote < ApplicationRecord

	belongs_to :user

	# validations
	validates :quote, presence: true

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:quote, :author, :user_id)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_with(model: quote, local: true) do |form| %>
  <% if quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <strong><%= form.label :quote %></strong>
    <%= form.text_field :quote, class: "form-control" %>
  </div>

  <div class="form-group">
    <strong><%= form.label :author %></strong>
    <%= form.text_field :author, class: "form-control" %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <hr>
  
  <div class="actions">
    <%= form.submit 'Save Quote', class: "btn btn-success" %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to 'All Students', students_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to 'All Lessons', lessons_path, class:"nav-link"%>
  </li>
  <li class="nav-item">
    <%= link_to 'Create New Lesson', new_lesson_path, class:"nav-link" %>
  </li>
</ul>

<div class="header-bar">
  <h1>Edit Quote</h1>
</div>

<%= render 'form', quote: @quote, class: 'button btn btn-info' %>

<%= link_to 'Back to All Quotes', quotes_path, class: 'button btn btn-info' %>

app/views/quotes/index.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to 'All Students', students_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to 'All Lessons', lessons_path, class:"nav-link"%>
  </li>
  <li class="nav-item">
    <%= link_to 'Create New Lesson', new_lesson_path, class:"nav-link" %>
  </li>
</ul>

<div class="header-bar">
  <h1>Manage Quotes</h1>
</div>

<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
    <tr>
      <th>Quote</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.quote %></td>
        <td><%= quote.author %></td>
        <td><%= link_to 'View', quote, class: 'button btn btn-info' %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote), class: 'button btn btn-info' %></td>
        <td><%= link_to 'Delete', quote, method: :delete, class: 'button btn btn-danger', data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<hr>

<%= link_to 'New Quote', new_quote_path, class: 'button btn btn-success' %>

app/views/quotes/new.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to 'All Students', students_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to 'All Lessons', lessons_path, class:"nav-link"%>
  </li>
  <li class="nav-item">
    <%= link_to 'Create New Lesson', new_lesson_path, class:"nav-link" %>
  </li>
</ul>

<div class="header-bar">
  <h1>New Quote</h1>
</div>

<%= render 'form', quote: @quote %>

<%= link_to 'Back to All Quotes', quotes_path, class: "btn btn-info" %>

app/views/quotes/show.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to 'All Students', students_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to 'All Lessons', lessons_path, class:"nav-link"%>
  </li>
  <li class="nav-item">
    <%= link_to 'Create New Lesson', new_lesson_path, class:"nav-link" %>
  </li>
</ul>

<div class="header-bar">
  <h1>View Quote</h1>
</div>

<p id="notice"><%= notice %></p>

<p>
  <strong>Quote:</strong>
  <%= @quote.quote %>
</p>

<p>
  <strong>Author:</strong>
  <%= @quote.author %>
</p>
<hr>
<%= link_to 'Edit this Quote', edit_quote_path(@quote), class: 'button btn btn-info' %> 
<%= link_to 'Back to All Quotes', quotes_path, class: 'button btn btn-info' %>