config/routes.rb
Rails.application.routes.draw do
  get 'home/help'
  devise_for :users
  resources :lessons
  resources :students
  resources :quotes

  root 'students#index'

  get 'new_lesson' => 'lessons#new'
  get 'show_student' => 'students#show'
  get 'lessons_by_student' => 'lessons#lessons_by_student', as: 'student_lessons'
  get 'new_quote'=> 'quotes#new'
  get 'quotes' => 'quotes#index'
  get 'help' => 'home#help'

  mount Resque::Server, :at => "/resque"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord

	# associations
	has_many :lessons
	
	def first_last_name
    "#{firstname} #{lastname}"
  	end

  	# validations:
  	validates :email, presence: true, format: /\w+@\w+\.{1}[a-zA-Z]{2,}/
  	# less strict: .+@.+\.{1}.{2,}

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all.order(lastname: :asc).page(params[:page]).per(5)

  end

  # GET /students/1
  # GET /students/1.json
  def show
    @lesson = @student.lessons.last
    # @lesson = Lesson.new
    @lessons = @student.lessons.order(lesson_date: :desc).page(params[:page]).per(1)

  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:firstname, :lastname, :status, :phone, :email, :dob, :experience, :interests, :lesson_time)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    First Name<br>
    <%= form.text_field :firstname, class: "form-control" %>
  </div>

  <div class="form-group">
    Last Name<br>
    <%= form.text_field :lastname, class: "form-control"  %>
  </div>

  <div class="field">

    <%= form.radio_button :status, "active" %>
    <%= form.label :status_active, "Active" %>
    <%= form.radio_button :status, "inactive" %>
    <%= form.label :status_inactive, "Inactive" %>
  
  </div>

  <div class="form-group">
    Phone (10 digits, no hyphens)<br>
    <%= form.number_field :phone, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control"  %>
  </div>

  <div class="form-group">
    Date of Birth<br>
    <%= form.date_field :dob, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :experience%>
    <%= form.text_area :experience, class: "form-control", rows: "6" %>
  </div>

  <div class="form-group">
    <%= form.label :interests %>
    <%= form.text_area :interests, class: "form-control", rows: "6"  %>
  </div>

  <div class="form-group">
    <%= form.label :lesson_time %>
    <%= form.text_field :lesson_time, class: "form-control"  %>
  </div>

  <div class="actions">
    <%= form.submit 'Save Student Info', class: "btn btn-success" %>
  </div>
<% end %>

app/views/students/edit.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to 'All Students', students_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to 'All Lessons', lessons_path, class:"nav-link"%>
  </li>
  <li class="nav-item">
    <%= link_to 'Create New Lesson', new_lesson_path, class:"nav-link" %>
  </li>
</ul>

<div class="header-bar">
  <h1>Edit Student Information</h1>
</div>

<%= render 'form', student: @student %>

<%= link_to 'Back to Student Record', @student, class: "button btn btn-info" %>
<%= link_to 'Delete Student', @student, method: :delete, data: { confirm: 'Are you sure? Click "Cancel" to keep this student.' }, class: 'button btn btn-danger' %>
<%= link_to 'All Students', students_path, class: "button btn btn-info" %>

app/views/students/index.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to 'All Students', students_path, class: "nav-link", id: "active" %>
  </li>
  <li class="nav-item">
    <%= link_to 'All Lessons', lessons_path, class:"nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to 'Create New Lesson', new_lesson_path, class:"nav-link" %>
  </li>
</ul>

<div class="header-bar">
  <h1>All Students</h1>
</div>

<p id="notice"><%= notice %></p>

<table class="table bg-white">
  <thead>
    <tr>
      <th>Name</th>
      <th>Lesson Time</th>
      <th>Next Lesson</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.first_last_name %></td>  
        <td><%= student.lesson_time %></td>

        <% if student.lessons.last == nil %>
          <td> NO LESSONS </td>
        <% else %>
            <% if student.lessons.last.lesson_date.past? %>
              <td> * No future lessons scheduled * </td>
            <% else %>
              <td> <%= student.lessons.last.lesson_date.strftime('%a, %B %e, %l:%M %p ') %> </td>         
            <% end %>
        <% end %>

        <% if student.lessons.last == nil %>
          <td> </td>
        <% else %>
          <% if student.lessons.last.lesson_date.past? %>
              <td> <%= link_to 'Edit Last Lesson', edit_lesson_path(student.lessons.last), class: "button btn btn-info" %> </td>
              <% else %>
              <td> <%= link_to 'Edit Next Lesson', edit_lesson_path(student.lessons.last), class: "button btn btn-info" %> </td> 
              <% end %>
        <% end %>

        <td><%= link_to 'View Student', student, class: "button btn btn-info" %></td>
      </tr>
    <% end %>

  </tbody>

</table>
    <%= paginate @students %>

<br>

<%= link_to 'Create New Student', new_student_path, class: "button btn btn-success" %>

app/views/students/new.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to 'All Students', students_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to 'All Lessons', lessons_path, class:"nav-link"%>
  </li>
  <li class="nav-item">
    <%= link_to 'Create New Lesson', new_lesson_path, class:"nav-link" %>
  </li>
</ul>

<div class="header-bar">
  <h1>New Student</h1>
</div>



	<%= render 'form', student: @student %>

	<%= link_to 'Back to All Students', students_path, class: "button btn btn-info" %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to 'All Students', students_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to 'All Lessons', lessons_path, class:"nav-link"%>
  </li>
  <li class="nav-item">
    <%= link_to 'Create New Lesson', new_lesson_path, class:"nav-link" %>
  </li>
</ul>

<div class="header-bar">
  <h1>Student Information</h1>
</div>

<div class="row">
  <div class="col-md-5">
    <div class="card student-card">
        <div class="card-header">
          <h3><strong>Name:</strong>
          <%= @student.firstname %> <%= @student.lastname %></h3>
        </div>
        <div class="card-body">
          <p><strong>Status: </strong>
                    <% if @student.status != nil %>
                    <%= @student.status %> 
                    <% end %> 
          </p>

          <p>
            <strong>Lesson Time:</strong>
            <%= @student.lesson_time %>
          </p>
          <hr>
          <p>
            <strong>Phone:</strong>
            <%= number_to_phone(@student.phone, area_code: true) %>
          </p>

          <p>
            <strong>Email:</strong>
            <%= @student.email %>
          </p>

          <p>
            <strong>Date of Birth:</strong>
            <%= @student.dob %>
          </p>
           <hr>
          <p>
            <strong>Experience:</strong>
            <%= markdown (@student.experience) %>
          </p>

          <p>
            <strong>Interests:</strong>
            <%= markdown (@student.interests) %>
          </p>

                <%= link_to 'Edit Student Info', edit_student_path(@student), class: 'button btn btn-info' %>
 
        </div>

      </div>

  </div>

  <div class="col-md-2 middle-links">

    <%= link_to 'New Lesson for This Student', new_lesson_path(student_id: @student.id), class: 'button btn btn-info' %>

    <%= link_to 'All Lessons for This Student', student_lessons_path(id: params[:id]), class: 'button btn btn-info' %> 
  </div>

  <div class="col-md-5">

      <% @lessons.each do |lesson| %>
        <div class="card">
          <div class="card-header">
            <h3><strong>Lessons</strong></h3>
          </div>
          <div class="card-body">
            <strong>Lesson Date:</strong>
            <% if lesson.lesson_date != nil %>
           <%= lesson.lesson_date.strftime("%b %d, %Y | %l:%M %p") %>
           <% end %>
          <div class="header-reminder">
            <strong>Reminder:</strong><br>
           <%= markdown lesson.reminder %>
         </div>
           <p> <strong>Notes to Student: </strong><br>
            <%= markdown lesson.studentnote %> </p>
          <hr>

              <p><strong>Status: </strong><% if lesson.status != nil %>
              <%= lesson.status.humanize %>
              <% end %> 
              </p>
              <p> <strong>Grade: </strong><%= lesson.grade %></p>
            <p class="card-text">
            <p> <strong>Teacher Notes: </strong><br><%= markdown lesson.teachernote %> </p>
           

            <%= link_to 'Edit/Complete This Lesson', edit_lesson_path(lesson), class: 'button btn btn-info' %><br>
            <%= paginate @lessons %><br>
            

          </div>
        </div>
      <% end %>

  </div>

</div>   