config/routes.rb
Rails.application.routes.draw do
  get 'home/help'
  devise_for :users
  resources :lessons
  resources :students
  resources :quotes

  root 'students#index'

  get 'new_lesson' => 'lessons#new'
  get 'show_student' => 'students#show'
  get 'lessons_by_student' => 'lessons#lessons_by_student', as: 'student_lessons'
  get 'new_quote'=> 'quotes#new'
  get 'quotes' => 'quotes#index'
  get 'help' => 'home#help'

  mount Resque::Server, :at => "/resque"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lesson.rb
class Lesson < ApplicationRecord

	# associations
	belongs_to :student
	belongs_to :user

	# validations:
  	validates :lesson_date, presence: true

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]
  # before_action :set_user, only: [:new, :create]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all.order(lesson_date: :desc)
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
    # @student = Student.find(params[:id])
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
    @student = Student.find(params[:student_id]) if params.has_key?(:student_id)
    @lesson.student = @student
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save

        Resque.enqueue(TeacherReminder, @lesson.id)
        # LessonMailer.new_lesson(@lesson).deliver_now 

        Resque.enqueue(StudentReminder, @lesson.id)
        # StudentMailer.new_lesson(@lesson).deliver_now

        format.html { redirect_to @lesson.student, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }


      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update

    # student = Student.find(params[:id])

    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson.student, 
              notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def lessons_by_student
    @student = Student.find(params[:id])
    @lessons = @student.lessons.order(lesson_date: :desc)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    def set_user
        @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:student_id, :lesson_date, :status, :grade, :teachernote, :studentnote, :reminder, :user_id)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= form_with(model: lesson, local: true) do |form| %>
  <% if lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% lesson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card lesson-card">
    
    <div class="card-header">
      <div class="field">
        <%= form.collection_select :student_id, Student.all.order(lastname: :asc), :id, :first_last_name, :prompt => "SELECT STUDENT" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :lesson_date %>
      <%= form.datetime_field :lesson_date %>
    </div>

    <div class="form-group">
      <%= form.label :studentnote %>
      <br>
      <%= form.text_area :studentnote, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :reminder %>
      <br>
      <%= form.text_area :reminder, class: "form-control" %>
    </div>
  </div>

  <div class="card lesson-card">

    <div class="form-group">

      <%= form.radio_button :status, "completed" %>
      <%= form.label :status_completed, "Completed" %>
      <%= form.radio_button :status, "cancelled" %>
      <%= form.label :status_cancelled, "Cancelled" %>
      <%= form.radio_button :status, "no_show" %>
      <%= form.label :status_no_show, "No-Show" %><br>
    
    </div>

    <div class="form-group">
      <%= form.label :grade %>
      <%= form.text_field :grade %>
    </div>

    <div class="form-group>
      <%= form.label :teachernote %>
      <br>
      <%= form.text_area :teachernote, class: "form-control" %>
    </div>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <p></p>
    <div class="actions">
      <%= form.submit 'Save Lesson', class: 'btn btn-success'%>
    </div>

<% end %>

app/views/lessons/edit.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to 'All Students', students_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to 'All Lessons', lessons_path, class:"nav-link"%>
  </li>
  <li class="nav-item">
    <%= link_to 'Create New Lesson', new_lesson_path, class:"nav-link" %>
  </li>
</ul>

	<div class="header-bar">
		  <h1>Edit Lesson</h1>
		</div>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Delete Lesson', @lesson, method: :delete, data: { confirm: 'Are you sure? Click "Cancel" to keep this lesson.' }, class: 'button btn btn-danger' %>

app/views/lessons/index.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to 'All Students', students_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to 'All Lessons', lessons_path, class:"nav-link", id: "active" %>
  </li>
  <li class="nav-item">
    <%= link_to 'Create New Lesson', new_lesson_path, class:"nav-link" %>
  </li>
</ul>

<div class="header-bar">
  <h1>All Lessons</h1>
</div>

<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Lesson Date</th>
      <th>Status</th>
      <th>Grade</th>
      <th>Reminder</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= link_to lesson.student.first_last_name, show_student_path(id: lesson.student_id) %> </td>
        <td><%= lesson.lesson_date.strftime('%B %e, %l:%M %p ') %></td>
        <td><%= lesson.status.try(:humanize) %></td>
        <td><%= lesson.grade %></td>
        <td><%= lesson.reminder.first(20) %>
          <% if lesson.reminder.length > 20 %>
            ...</p>
          <% end %>
        </td>
        <td><%= link_to 'View', lesson, class: 'button btn btn-info' %></td>
        <td><%= link_to 'Edit', edit_lesson_path(lesson), class: 'button btn btn-info' %></td>
        <td><%= link_to 'Delete', lesson, method: :delete, data: { confirm: 'Are you sure you want to delete this lesson? Click "cancel" to keep it.' }, class: 'button btn btn-danger' %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lesson', new_lesson_path, class: "button btn btn-success" %>

app/views/lessons/lessons_by_student.html.erb
<p id="notice"><%= notice %></p>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to 'All Students', students_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to 'All Lessons', lessons_path, class:"nav-link"%>
  </li>
  <li class="nav-item">
    <%= link_to 'Create New Lesson', new_lesson_path, class:"nav-link" %>
  </li>
</ul>

<div class="header-bar">
  <h1>Lessons By Student</h1>
</div>

<h3>Student: <%= @student.firstname %> <%=@student.lastname %> </h3>

<table class="table">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Lesson Date</th>
      <th>Status</th>
      <th>Grade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= link_to lesson.student.firstname, show_student_path(id: lesson.student_id) %></td>
        <td><%= lesson.student.lastname %></td>
        <td><%= lesson.lesson_date.strftime('%a, %B %e, %l:%M %p ') %></td>
        <td><%= lesson.status.try(:humanize) %></td>
        <td><%= lesson.grade %></td>
        <td><%= link_to 'View Notes', lesson, class: 'button btn btn-info' %></td>
        <td><%= link_to 'Edit Notes/Date', edit_lesson_path(lesson), class: 'button btn btn-info' %></td>
        <td><%= link_to 'Delete', lesson, method: :delete, data: { confirm: 'Are you sure you want to delete this lesson? Click "cancel" to keep it.' }, class: 'button btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lesson', new_lesson_path, class: 'btn btn-success' %>

app/views/lessons/new.html.erb
	<ul class="nav nav-tabs">
	  <li class="nav-item">
	    <%= link_to 'All Students', students_path, class: "nav-link" %>
	  </li>
	  <li class="nav-item">
	    <%= link_to 'All Lessons', lessons_path, class: "nav-link" %>
	  </li>
	  <li class="nav-item">
	    <%= link_to 'Create New Lesson', new_lesson_path, class: "nav-link", id: "active" %>
	  </li>
	</ul>

		<div class="header-bar">
		  <h1>New Lesson</h1>
		</div>

	<%= render 'form', lesson: @lesson %>

app/views/lessons/show.html.erb
<p id="notice"><%= notice %></p>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to 'All Students', students_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to 'All Lessons', lessons_path, class:"nav-link"%>
  </li>
  <li class="nav-item">
    <%= link_to 'Create New Lesson', new_lesson_path, class:"nav-link" %>
  </li>
</ul>

<div class="header-bar">
  <h1>View Lesson</h1>
</div>

<p>
  <strong>Student:</strong>
  <%= @lesson.student.firstname %> <%= @lesson.student.lastname %>
</p>

<p>
  <strong>Lesson Date:</strong>
  <%= @lesson.lesson_date.strftime("%b %d, %Y") %>
</p>

<p>
  <strong>Status:</strong>
  <%= @lesson.status %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @lesson.grade %>
</p>

<p>
  <strong>Teachernote:</strong>
  <%= @lesson.teachernote %>
</p>

<p>
  <strong>Studentnote:</strong>
  <%= @lesson.studentnote %>
</p>

<p>
  <strong>Reminder:</strong>
  <%= @lesson.reminder %>
</p>


<%= link_to 'Edit', edit_lesson_path(@lesson), class: 'button btn btn-success' %>
<%= link_to 'Delete', @lesson, method: :delete, data: { confirm: 'Are you sure you want to delete this lesson? Click "cancel" to keep it.' }, class: 'button btn btn-danger' %>
<br>
<%= link_to 'Set up Next Lesson', new_lesson_path, class: 'button btn btn-success' %>

<%= link_to 'Go to Student Info', show_student_path(id: @lesson.student_id), class: 'button btn btn-success' %>

<%= link_to 'Show All Lessons for this Student', student_lessons_path(id: @lesson.student_id), class: 'button btn btn-info' %> 