config/routes.rb
Rails.application.routes.draw do
  get 'home/help'
  devise_for :users
  resources :lessons
  resources :students
  resources :quotes

  root 'students#index'

  get 'new_lesson' => 'lessons#new'
  get 'show_student' => 'students#show'
  get 'lessons_by_student' => 'lessons#lessons_by_student', as: 'student_lessons'
  get 'new_quote'=> 'quotes#new'
  get 'quotes' => 'quotes#index'
  get 'help' => 'home#help'

  mount Resque::Server, :at => "/resque"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lesson Notes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <%= link_to root_path do %>
        <%= image_tag 'ln-logo-white.gif', height: '130px', alt: 'Lesson Notes logo'%>
     
      <div class="navbar-brand" href="/">Lesson Notes</div>
       <% end %>
     
      <ul class="navbar-nav mr-auto">
        <!-- in case there are other links someday -->
      </ul>


      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= current_user.email %>
          </li>
          <br>
          <li>
            <%=link_to 'Edit Your Profile', edit_user_registration_path %>
          </li>
          <li>
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li>
             <%= link_to 'Sign In', new_user_session_path %>
           </li>
          <% end %>
      </ul>
      
    </nav>


      <div class="quote-bar">
        <% if Quote.any? %>
          <blockquote class="blockquote mb-0">
            <%= Quote.all.sample.quote %> 
            <footer class="blockquote-footer">
              <%= Quote.all.sample.author %>
            </footer>
        </blockquote>
          <% end %>
      </div>



    <div class="container">


     <%= yield %>
     
   </div>


<footer class="page-footer">
  <div class="row">
    <div class="col-md-4">
      <ul class="nav flex-column">
        <li class="nav-item">
          <%= link_to "All Students", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "All Lessons", lessons_path, class: "nav-link" %>
        </li>      
        <li class="nav-item">
          <%= link_to "New Lesson", new_lesson_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
    <div class="col-md-4">
      <p>© Lesson Notes 2018</p>
    </div>
    <div class="col-md-4">
      <ul class="nav flex-column">
        <li class="nav-item">
          <%= link_to "New Student", new_student_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Manage Quotes", quotes_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Help", help_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</footer>

  </body>
</html>